#controllers:
#    resource: ../../src/Controller/
#    type: annotation

#api_v1:
#    resource: ../../src/Api/Controller/
#    type: annotation
#    prefix: /api/v1

kernel:
    resource: ../../src/Kernel.php
    type: annotation
